name: CI Pipeline

on:
  push:
    branches:
      - main
    pull request:

jobs:
  build:
    runs-on: npm-latest

    steps:

    #check out repo
    - name: Check out repository
      uses: actions/checkout@v4

